version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: offerletter-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_portals
    ports:
      - "5607:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: offerletter-backend
    ports:
      - "3607:3607"
    environment:
      PORT: 3607
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: employee_portals
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

  congratulations:
    build: ./Congratulations
    container_name: offerletter-congratulations
    ports:
      - "8613:80"
    depends_on:
      - backend

  hr:
    build: ./HR
    container_name: offerletter-hr
    ports:
      - "8614:80"
    depends_on:
      - backend

  employee:
    build: ./employee
    container_name: offerletter-employee
    ports:
      - "8615:80"
    depends_on:
      - backend

volumes:
  pgdata:

